// Snapshot of textual-themes 0.15.2 (Apache-2.0, Michael Blaess).
// Generated by tools/snapshot_palettes.py - do not edit by hand.

export type Palette = {
  name: string
  title: string
  dark: boolean
  primary: string
  secondary: string
  accent: string
  foreground: string
  background: string
  surface: string
  panel: string
  warning: string
  error: string
  success: string
}

export const PALETTES: readonly Palette[] = [
  { name: 'brotkasten', title: 'Brotkasten', dark: true, primary: '#7C70DA', secondary: '#3A2B8A', accent: '#EDF171', foreground: '#D0CCFF', background: '#3A2B8A', surface: '#5446B8', panel: '#241870', warning: '#EDF171', error: '#C46C71', success: '#A9FF9F' },
  { name: 'boing', title: 'Boing', dark: true, primary: '#FF8800', secondary: '#0055AA', accent: '#FF8800', foreground: '#FFFFFF', background: '#0055AA', surface: '#0066BB', panel: '#004499', warning: '#FFAA00', error: '#FF4444', success: '#44BB44' },
  { name: 'gemstone', title: 'Gemstone', dark: false, primary: '#007700', secondary: '#555555', accent: '#009900', foreground: '#111111', background: '#E8E8E8', surface: '#F2F2F2', panel: '#DDDDDD', warning: '#AA8800', error: '#CC0000', success: '#007700' },
  { name: 'classic-terminal', title: 'Classic Terminal', dark: true, primary: '#33FF33', secondary: '#2A7A2A', accent: '#88FF88', foreground: '#33FF33', background: '#0A0A0A', surface: '#162616', panel: '#0F1B0F', warning: '#FFAA00', error: '#FF4444', success: '#33FF33' },
  { name: 'next', title: 'Next', dark: true, primary: '#9966CC', secondary: '#555555', accent: '#9966CC', foreground: '#E0E0E0', background: '#2A2A2A', surface: '#3A3A3A', panel: '#222222', warning: '#CC9933', error: '#CC4444', success: '#44AA44' },
  { name: 'bebox', title: 'BeBox', dark: true, primary: '#FFD800', secondary: '#5F5F5F', accent: '#FFD800', foreground: '#E8E8E8', background: '#3A3A4A', surface: '#4A4A5A', panel: '#333344', warning: '#FF9900', error: '#DD3333', success: '#33BB33' },
  { name: 'bunty', title: 'Bunty', dark: true, primary: '#DD4814', secondary: '#77216F', accent: '#E18B5C', foreground: '#F2EAEA', background: '#2C001E', surface: '#4A2540', panel: '#1F0014', warning: '#F99B11', error: '#DF382C', success: '#38B44A' },
  { name: 'cupertino', title: 'Cupertino', dark: false, primary: '#007AFF', secondary: '#5856D6', accent: '#007AFF', foreground: '#1D1D1F', background: '#F5F5F7', surface: '#FFFFFF', panel: '#E8E8ED', warning: '#FF9500', error: '#FF3B30', success: '#34C759' },
  { name: 'luna', title: 'Luna', dark: true, primary: '#0054E3', secondary: '#21A121', accent: '#0054E3', foreground: '#FFFFFF', background: '#003399', surface: '#0044AA', panel: '#002D8A', warning: '#FFCC00', error: '#E81123', success: '#21A121' },
  { name: 'commandr', title: 'Commandr', dark: true, primary: '#FFFF55', secondary: '#55FFFF', accent: '#FFFF55', foreground: '#FFFFFF', background: '#0000AA', surface: '#1A1ACC', panel: '#000077', warning: '#FFAA00', error: '#FF5555', success: '#55FF55' },
  { name: 'plan9', title: 'Plan 9', dark: false, primary: '#228844', secondary: '#4488AA', accent: '#228844', foreground: '#111111', background: '#FFFFEA', surface: '#EAFFFF', panel: '#D5E8D0', warning: '#BB8800', error: '#CC2222', success: '#228844' },
  { name: 'motif', title: 'Motif', dark: true, primary: '#CC9966', secondary: '#5F7B8A', accent: '#CC9966', foreground: '#D8D0C8', background: '#3A4A5A', surface: '#455565', panel: '#303F4F', warning: '#CCAA44', error: '#CC5544', success: '#55AA66' },
  { name: 'warp', title: 'Warp', dark: true, primary: '#00BBBB', secondary: '#3333AA', accent: '#00BBBB', foreground: '#D0D0D0', background: '#1A1A4E', surface: '#25255E', panel: '#141442', warning: '#DDAA22', error: '#DD4444', success: '#44BB66' },
  { name: 'geeko', title: 'Geeko', dark: true, primary: '#73BA25', secondary: '#35B9AB', accent: '#73BA25', foreground: '#EEEEEE', background: '#173F0F', surface: '#1E4D15', panel: '#12330B', warning: '#F0A30A', error: '#DD3333', success: '#73BA25' },
  { name: 'minty', title: 'Minty', dark: true, primary: '#8BB158', secondary: '#6DAB76', accent: '#8BB158', foreground: '#E8E8E8', background: '#2B2B2B', surface: '#363636', panel: '#232323', warning: '#E5A50A', error: '#CC3333', success: '#8BB158' },
  { name: 'crimson', title: 'Crimson', dark: true, primary: '#CC0000', secondary: '#A30000', accent: '#EE0000', foreground: '#E0E0E0', background: '#1A0A0A', surface: '#2A1515', panel: '#140808', warning: '#EEA500', error: '#FF4444', success: '#44AA44' },
  { name: 'razzy', title: 'Razzy', dark: true, primary: '#C51A4A', secondary: '#6CC24A', accent: '#C51A4A', foreground: '#EEEEEE', background: '#1E1E2E', surface: '#2A2A3A', panel: '#181828', warning: '#E5A50A', error: '#DD3333', success: '#6CC24A' },
  { name: 'beastie', title: 'Beastie', dark: true, primary: '#AB2B28', secondary: '#5E8AAA', accent: '#AB2B28', foreground: '#D4D4D4', background: '#1C2028', surface: '#262A32', panel: '#161A20', warning: '#CC9933', error: '#DD4444', success: '#55AA66' },
  { name: 'fifty-eight', title: 'Fifty-Eight', dark: true, primary: '#C9A96E', secondary: '#6A6A6A', accent: '#9E1B25', foreground: '#E8C985', background: '#100C08', surface: '#1E1914', panel: '#080605', warning: '#C9A048', error: '#B8252E', success: '#6A9A5A' },
  { name: 'bluesy', title: 'Bluesy', dark: true, primary: '#D4AF37', secondary: '#1E4FA0', accent: '#F0C85A', foreground: '#F5D76E', background: '#081F54', surface: '#0E2E6E', panel: '#04133A', warning: '#E8A838', error: '#DD3344', success: '#48B870' },
  { name: 'goldfinder', title: 'Goldfinder', dark: true, primary: '#E6B800', secondary: '#8A6E20', accent: '#FFD740', foreground: '#E8DFC0', background: '#080705', surface: '#18140A', panel: '#040302', warning: '#E8A838', error: '#CC4040', success: '#5AAA5A' },
  { name: 'goldrunner', title: 'Goldrunner', dark: true, primary: '#C8A93A', secondary: '#C788CE', accent: '#E8C547', foreground: '#EEEECA', background: '#080520', surface: '#1A0F3D', panel: '#120A2E', warning: '#B06400', error: '#D6456A', success: '#5FA82E' },
  { name: 'hercules', title: 'Hercules', dark: true, primary: '#FF9A2E', secondary: '#A85F12', accent: '#FFC470', foreground: '#F5A742', background: '#0B0A09', surface: '#1D1B19', panel: '#12110F', warning: '#FFC470', error: '#FF4A1F', success: '#F5A742' },
  { name: 'hulkula', title: 'Hulkula', dark: true, primary: '#2BA841', secondary: '#BCC4CA', accent: '#4DC962', foreground: '#F0F2EE', background: '#083C14', surface: '#104B1B', panel: '#042608', warning: '#D4A040', error: '#CC2222', success: '#4DC962' },
  { name: 'flughund', title: 'Flughund', dark: true, primary: '#244B85', secondary: '#BCC4CA', accent: '#3D6FB8', foreground: '#F0F2F5', background: '#060810', surface: '#0E1422', panel: '#030509', warning: '#D4A040', error: '#CC3030', success: '#50AA50' },
  { name: 'classic-navy', title: 'Classic Navy', dark: true, primary: '#C0C5CC', secondary: '#1E4585', accent: '#9E3A42', foreground: '#EEF0F5', background: '#0C2B5C', surface: '#143465', panel: '#061A3A', warning: '#D4A040', error: '#B04048', success: '#50AA50' },
  { name: 'brick', title: 'Brick', dark: false, primary: '#8E2A5E', secondary: '#5A4858', accent: '#D63B68', foreground: '#241F28', background: '#D4CEBC', surface: '#E2DCCA', panel: '#B2AC9A', warning: '#C85820', error: '#A0203A', success: '#4A7A3A' },
  { name: 'clipper', title: 'Clipper', dark: false, primary: '#1A4FA0', secondary: '#C61F2C', accent: '#D4222F', foreground: '#1A1A1A', background: '#F6F3E8', surface: '#FCFAF0', panel: '#EBE6D4', warning: '#C88A20', error: '#C61F2C', success: '#2E8B3D' },
  { name: 'synthwave', title: 'Synthwave', dark: true, primary: '#FF2E93', secondary: '#7B2D8E', accent: '#05D9E8', foreground: '#F5E9FF', background: '#1A0B3D', surface: '#261553', panel: '#0E0524', warning: '#FFD319', error: '#FF3860', success: '#39FF14' },
  { name: 'miami', title: 'Miami', dark: true, primary: '#FF6FAB', secondary: '#1FB8BC', accent: '#FFA06A', foreground: '#FFE8E0', background: '#0B2F3F', surface: '#124050', panel: '#051825', warning: '#FFD76B', error: '#E63970', success: '#4ECDA8' },
  { name: 'racing', title: 'Racing', dark: true, primary: '#1A5CC8', secondary: '#C0C6D0', accent: '#E42030', foreground: '#EEF0F5', background: '#14161E', surface: '#1F232E', panel: '#080A10', warning: '#E8A838', error: '#E42030', success: '#3AAA4A' },
  { name: 'metropolis', title: 'Metropolis', dark: true, primary: '#E02030', secondary: '#1A5CC8', accent: '#FFD53B', foreground: '#F0F2F8', background: '#0A2A5E', surface: '#123876', panel: '#051838', warning: '#FFD53B', error: '#C80A18', success: '#3AAA4A' },
  { name: 'spiderized', title: 'Spiderized', dark: true, primary: '#D71920', secondary: '#1F75FE', accent: '#1F75FE', foreground: '#FFFFFF', background: '#0E1A3A', surface: '#1A2C5F', panel: '#070D24', warning: '#FFA830', error: '#C80A18', success: '#4AA85A' },
  { name: 'ascot', title: 'Ascot', dark: true, primary: '#F2C200', secondary: '#C0C5CC', accent: '#F2C200', foreground: '#F5EBD2', background: '#173E2D', surface: '#1F4E3A', panel: '#0E2C1E', warning: '#F2C200', error: '#C81E2A', success: '#2E7D52' },
  { name: 'joker', title: 'Joker', dark: true, primary: '#7B3FB2', secondary: '#2FCC2F', accent: '#FFC72C', foreground: '#F5F0E5', background: '#0E0824', surface: '#1F0F3F', panel: '#2D1758', warning: '#FFC72C', error: '#DC4040', success: '#2FCC2F' },
  { name: 'marley', title: 'Marley', dark: true, primary: '#078930', secondary: '#DA121A', accent: '#FCDD09', foreground: '#F5EFD8', background: '#0C0A06', surface: '#181818', panel: '#050505', warning: '#FCDD09', error: '#DA121A', success: '#078930' },
  { name: 'lenseflare', title: 'Lenseflare', dark: true, primary: '#FF8C42', secondary: '#2BD0E0', accent: '#E5283A', foreground: '#F0E5D2', background: '#0A1226', surface: '#14213D', panel: '#060B18', warning: '#FFB838', error: '#E5283A', success: '#2BD0E0' },
  { name: 'platoon', title: 'Platoon', dark: true, primary: '#9AA04A', secondary: '#6F8A3C', accent: '#C7B06A', foreground: '#E4E0CF', background: '#12130B', surface: '#22241A', panel: '#3A3D22', warning: '#E0B330', error: '#BF3B2A', success: '#6F9A4A' },
  { name: 'corleone', title: 'Corleone', dark: true, primary: '#A88B52', secondary: '#4A4E58', accent: '#9A8147', foreground: '#C3C0B4', background: '#0B0C0E', surface: '#16181C', panel: '#1F2228', warning: '#B89043', error: '#8C2F2F', success: '#5E7355' },
  { name: 'golden-brown', title: 'Golden Brown', dark: true, primary: '#A8843F', secondary: '#6E4E36', accent: '#C29A4E', foreground: '#D5C5A4', background: '#0F0B07', surface: '#1C1611', panel: '#2B2018', warning: '#BE8F39', error: '#9A2B2B', success: '#5F6B42' },
  { name: 'christophorus', title: 'Christophorus', dark: true, primary: '#D4A15A', secondary: '#50698A', accent: '#E0B574', foreground: '#E6E9EE', background: '#102640', surface: '#132D4B', panel: '#1A3A5E', warning: '#E8B45A', error: '#FF6B8B', success: '#8FD16A' },
]
