"""Writes the palettes from textual-themes to hooks/palettes.ts as a one-time snapshot.

Usage:  python -I tools/snapshot_palettes.py <folder-with-textual_themes> hooks/palettes.ts

The first argument is the folder that contains the textual_themes package (site-packages
or an unpacked wheel). Running it again overwrites manual changes to the target file.
"""

from __future__ import annotations

import importlib.metadata
import sys
from pathlib import Path

FIELDS = (
    "primary",
    "secondary",
    "accent",
    "foreground",
    "background",
    "surface",
    "panel",
    "warning",
    "error",
    "success",
)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2

    source = Path(sys.argv[1]).resolve()
    target = Path(sys.argv[2])
    sys.path.insert(0, str(source))

    from textual_themes.palettes import DISPLAY_NAMES, RETRO_PALETTES  # noqa: PLC0415

    try:
        version = importlib.metadata.version("textual-themes")
    except importlib.metadata.PackageNotFoundError:
        version = "unknown"

    lines = [
        f"// Snapshot of textual-themes {version} (Apache-2.0, Michael Blaess).",
        "// Generated by tools/snapshot_palettes.py - do not edit by hand.",
        "",
        "export type Palette = {",
        "  name: string",
        "  title: string",
        "  dark: boolean",
        *[f"  {field}: string" for field in FIELDS],
        "}",
        "",
        "export const PALETTES: readonly Palette[] = [",
    ]
    for palette in RETRO_PALETTES:
        # The display name carries a description after an em dash (U+2014), only the name counts here
        full = DISPLAY_NAMES.get(palette.name, palette.name)
        title = full.split(chr(0x2014))[0].strip().replace("'", "\\'")
        parts = [f"name: '{palette.name}'", f"title: '{title}'", f"dark: {str(palette.dark).lower()}"]
        parts += [f"{field}: '{getattr(palette, field)}'" for field in FIELDS]
        lines.append("  { " + ", ".join(parts) + " },")
    lines += ["]", ""]

    target.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{len(RETRO_PALETTES)} palettes written to {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
